# Generated by Django 4.2.18 on 2025-01-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_flower_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='picture',
            field=models.ImageField(upload_to='catalog/static/catalog/img', verbose_name='Изображение'),
        ),
    ]
