# Generated by Django 5.1.5 on 2025-02-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_flower_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flower',
            old_name='quantity',
            new_name='availability',
        ),
    ]
